# Generated by Django 5.1.1 on 2024-09-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_color_name_alter_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
