# Generated by Django 5.1.1 on 2024-09-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_offerbanner_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=255)),
                ('returns', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
            ],
        ),
    ]
