# Generated by Django 5.1.1 on 2024-09-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_supportsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supportsection',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
